"use strict";var sjcl={cipher:{},hash:{},keyexchange:{},mode:{},misc:{},codec:{},exception:{corrupt:function(b){this.toString=function(){return"CORRUPT: "+this.message};this.message=b},invalid:function(b){this.toString=function(){return"INVALID: "+this.message};this.message=b},bug:function(b){this.toString=function(){return"BUG: "+this.message};this.message=b},notReady:function(b){this.toString=function(){return"NOT READY: "+this.message};this.message=b}}};
sjcl.cipher.aes=function(b){this.m[0][0][0]||this.M();var c,d,a,e,f=this.m[0][4],g=this.m[1];c=b.length;var h=1;if(4!==c&&6!==c&&8!==c)throw new sjcl.exception.invalid("invalid aes key size");this.b=[a=b.slice(0),e=[]];for(b=c;b<4*c+28;b++){d=a[b-1];if(0===b%c||8===c&&4===b%c)d=f[d>>>24]<<24^f[d>>16&255]<<16^f[d>>8&255]<<8^f[d&255],0===b%c&&(d=d<<8^d>>>24^h<<24,h=h<<1^283*(h>>7));a[b]=a[b-c]^d}for(c=0;b;c++,b--)d=a[c&3?b:b-4],e[c]=4>=b||4>c?d:g[0][f[d>>>24]]^g[1][f[d>>16&255]]^g[2][f[d>>8&255]]^g[3][f[d&
255]]};
sjcl.cipher.aes.prototype={encrypt:function(b){return ba(this,b,0)},decrypt:function(b){return ba(this,b,1)},m:[[[],[],[],[],[]],[[],[],[],[],[]]],M:function(){var b=this.m[0],c=this.m[1],d=b[4],a=c[4],e,f,g,h=[],k=[],l,m,n,q;for(e=0;0x100>e;e++)k[(h[e]=e<<1^283*(e>>7))^e]=e;for(f=g=0;!d[f];f^=l||1,g=k[g]||1)for(n=g^g<<1^g<<2^g<<3^g<<4,n=n>>8^n&255^99,d[f]=n,a[n]=f,m=h[e=h[l=h[f]]],q=0x1010101*m^0x10001*e^0x101*l^0x1010100*f,m=0x101*h[n]^0x1010100*n,e=0;4>e;e++)b[e][f]=m=m<<24^m>>>8,c[e][n]=q=q<<24^q>>>8;for(e=
0;5>e;e++)b[e]=b[e].slice(0),c[e]=c[e].slice(0)}};
function ba(b,c,d){if(4!==c.length)throw new sjcl.exception.invalid("invalid aes block size");var a=b.b[d],e=c[0]^a[0],f=c[d?3:1]^a[1],g=c[2]^a[2];c=c[d?1:3]^a[3];var h,k,l,m=a.length/4-2,n,q=4,F=[0,0,0,0];h=b.m[d];b=h[0];var z=h[1],B=h[2],A=h[3],C=h[4];for(n=0;n<m;n++)h=b[e>>>24]^z[f>>16&255]^B[g>>8&255]^A[c&255]^a[q],k=b[f>>>24]^z[g>>16&255]^B[c>>8&255]^A[e&255]^a[q+1],l=b[g>>>24]^z[c>>16&255]^B[e>>8&255]^A[f&255]^a[q+2],c=b[c>>>24]^z[e>>16&255]^B[f>>8&255]^A[g&255]^a[q+3],q+=4,e=h,f=k,g=l;for(n=
0;4>n;n++)F[d?3&-n:n]=C[e>>>24]<<24^C[f>>16&255]<<16^C[g>>8&255]<<8^C[c&255]^a[q++],h=e,e=f,f=g,g=c,c=h;return F}
sjcl.bitArray={bitSlice:function(b,c,d){b=sjcl.bitArray.Y(b.slice(c/32),32-(c&31)).slice(1);return void 0===d?b:sjcl.bitArray.clamp(b,d-c)},extract:function(b,c,d){var a=Math.floor(-c-d&31);return((c+d-1^c)&-32?b[c/32|0]<<32-a^b[c/32+1|0]>>>a:b[c/32|0]>>>a)&(1<<d)-1},concat:function(b,c){if(0===b.length||0===c.length)return b.concat(c);var d=b[b.length-1],a=sjcl.bitArray.getPartial(d);return 32===a?b.concat(c):sjcl.bitArray.Y(c,a,d|0,b.slice(0,b.length-1))},bitLength:function(b){var c=b.length;return 0===
c?0:32*(c-1)+sjcl.bitArray.getPartial(b[c-1])},clamp:function(b,c){if(32*b.length<c)return b;b=b.slice(0,Math.ceil(c/32));var d=b.length;c=c&31;0<d&&c&&(b[d-1]=sjcl.bitArray.partial(c,b[d-1]&2147483648>>c-1,1));return b},partial:function(b,c,d){return 32===b?c:(d?c|0:c<<32-b)+0x10000000000*b},getPartial:function(b){return Math.round(b/0x10000000000)||32},equal:function(b,c){if(sjcl.bitArray.bitLength(b)!==sjcl.bitArray.bitLength(c))return!1;var d=0,a;for(a=0;a<b.length;a++)d|=b[a]^c[a];return 0===
d},Y:function(b,c,d,a){var e;e=0;for(void 0===a&&(a=[]);32<=c;c-=32)a.push(d),d=0;if(0===c)return a.concat(b);for(e=0;e<b.length;e++)a.push(d|b[e]>>>c),d=b[e]<<32-c;e=b.length?b[b.length-1]:0;b=sjcl.bitArray.getPartial(e);a.push(sjcl.bitArray.partial(c+b&31,32<c+b?d:a.pop(),1));return a},P:function(b,c){return[b[0]^c[0],b[1]^c[1],b[2]^c[2],b[3]^c[3]]},byteswapM:function(b){var c,d;for(c=0;c<b.length;++c)d=b[c],b[c]=d>>>24|d>>>8&0xff00|(d&0xff00)<<8|d<<24;return b}};
sjcl.codec.utf8String={fromBits:function(b){var c="",d=sjcl.bitArray.bitLength(b),a,e;for(a=0;a<d/8;a++)0===(a&3)&&(e=b[a/4]),c+=String.fromCharCode(e>>>8>>>8>>>8),e<<=8;return decodeURIComponent(escape(c))},toBits:function(b){b=unescape(encodeURIComponent(b));var c=[],d,a=0;for(d=0;d<b.length;d++)a=a<<8|b.charCodeAt(d),3===(d&3)&&(c.push(a),a=0);d&3&&c.push(sjcl.bitArray.partial(8*(d&3),a));return c}};
sjcl.codec.hex={fromBits:function(b){var c="",d;for(d=0;d<b.length;d++)c+=((b[d]|0)+0xf00000000000).toString(16).substr(4);return c.substr(0,sjcl.bitArray.bitLength(b)/4)},toBits:function(b){var c,d=[],a;b=b.replace(/\s|0x/g,"");a=b.length;b=b+"00000000";for(c=0;c<b.length;c+=8)d.push(parseInt(b.substr(c,8),16)^0);return sjcl.bitArray.clamp(d,4*a)}};
sjcl.codec.base32={w:"ABCDEFGHIJKLMNOPQRSTUVWXYZ234567",W:"0123456789ABCDEFGHIJKLMNOPQRSTUV",BITS:32,BASE:5,REMAINING:27,fromBits:function(b,c,d){var a=sjcl.codec.base32.BASE,e=sjcl.codec.base32.REMAINING,f="",g=0,h=sjcl.codec.base32.w,k=0,l=sjcl.bitArray.bitLength(b);d&&(h=sjcl.codec.base32.W);for(d=0;f.length*a<l;)f+=h.charAt((k^b[d]>>>g)>>>e),g<a?(k=b[d]<<a-g,g+=e,d++):(k<<=a,g-=a);for(;f.length&7&&!c;)f+="=";return f},toBits:function(b,c){b=b.replace(/\s|=/g,"").toUpperCase();var d=sjcl.codec.base32.BITS,
a=sjcl.codec.base32.BASE,e=sjcl.codec.base32.REMAINING,f=[],g,h=0,k=sjcl.codec.base32.w,l=0,m,n="base32";c&&(k=sjcl.codec.base32.W,n="base32hex");for(g=0;g<b.length;g++){m=k.indexOf(b.charAt(g));if(0>m){if(!c)try{return sjcl.codec.base32hex.toBits(b)}catch(q){}throw new sjcl.exception.invalid("this isn't "+n+"!");}h>e?(h-=e,f.push(l^m>>>h),l=m<<d-h):(h+=a,l^=m<<d-h)}h&56&&f.push(sjcl.bitArray.partial(h&56,l,1));return f}};
sjcl.codec.base32hex={fromBits:function(b,c){return sjcl.codec.base32.fromBits(b,c,1)},toBits:function(b){return sjcl.codec.base32.toBits(b,1)}};
sjcl.codec.base64={w:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",fromBits:function(b,c,d){var a="",e=0,f=sjcl.codec.base64.w,g=0,h=sjcl.bitArray.bitLength(b);d&&(f=f.substr(0,62)+"-_");for(d=0;6*a.length<h;)a+=f.charAt((g^b[d]>>>e)>>>26),6>e?(g=b[d]<<6-e,e+=26,d++):(g<<=6,e-=6);for(;a.length&3&&!c;)a+="=";return a},toBits:function(b,c){b=b.replace(/\s|=/g,"");var d=[],a,e=0,f=sjcl.codec.base64.w,g=0,h;c&&(f=f.substr(0,62)+"-_");for(a=0;a<b.length;a++){h=f.indexOf(b.charAt(a));
if(0>h)throw new sjcl.exception.invalid("this isn't base64!");26<e?(e-=26,d.push(g^h>>>e),g=h<<32-e):(e+=6,g^=h<<32-e)}e&56&&d.push(sjcl.bitArray.partial(e&56,g,1));return d}};sjcl.codec.base64url={fromBits:function(b){return sjcl.codec.base64.fromBits(b,1,1)},toBits:function(b){return sjcl.codec.base64.toBits(b,1)}};
sjcl.codec.bytes={fromBits:function(b){var c=[],d=sjcl.bitArray.bitLength(b),a,e;for(a=0;a<d/8;a++)0===(a&3)&&(e=b[a/4]),c.push(e>>>24),e<<=8;return c},toBits:function(b){var c=[],d,a=0;for(d=0;d<b.length;d++)a=a<<8|b[d],3===(d&3)&&(c.push(a),a=0);d&3&&c.push(sjcl.bitArray.partial(8*(d&3),a));return c}};sjcl.hash.sha512=function(b){this.b[0]||this.M();b?(this.B=b.B.slice(0),this.u=b.u.slice(0),this.i=b.i):this.reset()};sjcl.hash.sha512.hash=function(b){return(new sjcl.hash.sha512).update(b).finalize()};
sjcl.hash.sha512.prototype={blockSize:1024,reset:function(){this.B=this.L.slice(0);this.u=[];this.i=0;return this},update:function(b){"string"===typeof b&&(b=sjcl.codec.utf8String.toBits(b));var c,d=this.u=sjcl.bitArray.concat(this.u,b);c=this.i;b=this.i=c+sjcl.bitArray.bitLength(b);if(0x1fffffffffffff<b)throw new sjcl.exception.invalid("Cannot hash more than 2^53 - 1 bits");if("undefined"!==typeof Uint32Array){var a=new Uint32Array(d),e=0;for(c=1024+c-(1024+c&1023);c<=b;c+=1024)N(this,a.subarray(32*
e,32*(e+1))),e+=1;d.splice(0,32*e)}else for(c=1024+c-(1024+c&1023);c<=b;c+=1024)N(this,d.splice(0,32));return this},finalize:function(){var b,c=this.u,d=this.B,c=sjcl.bitArray.concat(c,[sjcl.bitArray.partial(1,1)]);for(b=c.length+4;b&31;b++)c.push(0);c.push(0);c.push(0);c.push(Math.floor(this.i/0x100000000));for(c.push(this.i|0);c.length;)N(this,c.splice(0,32));this.reset();return d},L:[],ia:[12372232,13281083,9762859,1914609,15106769,4090911,4308331,8266105],b:[],ka:[2666018,15689165,5061423,9034684,
4764984,380953,1658779,7176472,197186,7368638,14987916,16757986,8096111,1480369,13046325,6891156,15813330,5187043,9229749,11312229,2818677,10937475,4324308,1135541,6741931,11809296,16458047,15666916,11046850,698149,229999,945776,13774844,2541862,12856045,9810911,11494366,7844520,15576806,8533307,15795044,4337665,16291729,5553712,15684120,6662416,7413802,12308920,13816008,4303699,9366425,10176680,13195875,4295371,6546291,11712675,15708924,1519456,15772530,6568428,6495784,8568297,13007125,7492395,2515356,
12632583,14740254,7262584,1535930,13146278,16321966,1853211,294276,13051027,13221564,1051980,4080310,6651434,14088940,4675607],M:function(){function b(a){return 0x100000000*(a-Math.floor(a))|0}function c(a){return 0x10000000000*(a-Math.floor(a))&255}for(var d=0,a=2,e,f;80>d;a++){f=!0;for(e=2;e*e<=a;e++)if(0===a%e){f=!1;break}f&&(8>d&&(this.L[2*d]=b(Math.pow(a,.5)),this.L[2*d+1]=c(Math.pow(a,.5))<<24|this.ia[d]),this.b[2*d]=b(Math.pow(a,1/3)),this.b[2*d+1]=c(Math.pow(a,1/3))<<24|this.ka[d],d++)}}};
function N(b,c){var d,a,e,f=b.B,g=b.b,h=f[0],k=f[1],l=f[2],m=f[3],n=f[4],q=f[5],F=f[6],z=f[7],B=f[8],A=f[9],C=f[10],P=f[11],ga=f[12],Q=f[13],ha=f[14],R=f[15],r;if("undefined"!==typeof Uint32Array)for(r=Array(160),d=0;32>d;d++)r[d]=c[d];else r=c;var v=h,t=k,G=l,D=m,H=n,E=q,X=F,I=z,w=B,u=A,S=C,J=P,T=ga,K=Q,Y=ha,L=R;for(d=0;80>d;d++){if(16>d)a=r[2*d],e=r[2*d+1];else{e=r[2*(d-15)];var p=r[2*(d-15)+1];a=(p<<31|e>>>1)^(p<<24|e>>>8)^e>>>7;var x=(e<<31|p>>>1)^(e<<24|p>>>8)^(e<<25|p>>>7);e=r[2*(d-2)];var y=
r[2*(d-2)+1],p=(y<<13|e>>>19)^(e<<3|y>>>29)^e>>>6,y=(e<<13|y>>>19)^(y<<3|e>>>29)^(e<<26|y>>>6),Z=r[2*(d-7)],aa=r[2*(d-16)],M=r[2*(d-16)+1];e=x+r[2*(d-7)+1];a=a+Z+(e>>>0<x>>>0?1:0);e+=y;a+=p+(e>>>0<y>>>0?1:0);e+=M;a+=aa+(e>>>0<M>>>0?1:0)}r[2*d]=a|=0;r[2*d+1]=e|=0;var Z=w&S^~w&T,ia=u&J^~u&K,y=v&G^v&H^G&H,ma=t&D^t&E^D&E,aa=(t<<4|v>>>28)^(v<<30|t>>>2)^(v<<25|t>>>7),M=(v<<4|t>>>28)^(t<<30|v>>>2)^(t<<25|v>>>7),na=g[2*d],ja=g[2*d+1],p=L+((w<<18|u>>>14)^(w<<14|u>>>18)^(u<<23|w>>>9)),x=Y+((u<<18|w>>>14)^(u<<
14|w>>>18)^(w<<23|u>>>9))+(p>>>0<L>>>0?1:0),p=p+ia,x=x+(Z+(p>>>0<ia>>>0?1:0)),p=p+ja,x=x+(na+(p>>>0<ja>>>0?1:0)),p=p+e|0,x=x+(a+(p>>>0<e>>>0?1:0));e=M+ma;a=aa+y+(e>>>0<M>>>0?1:0);Y=T;L=K;T=S;K=J;S=w;J=u;u=I+p|0;w=X+x+(u>>>0<I>>>0?1:0)|0;X=H;I=E;H=G;E=D;G=v;D=t;t=p+e|0;v=x+a+(t>>>0<p>>>0?1:0)|0}k=f[1]=k+t|0;f[0]=h+v+(k>>>0<t>>>0?1:0)|0;m=f[3]=m+D|0;f[2]=l+G+(m>>>0<D>>>0?1:0)|0;q=f[5]=q+E|0;f[4]=n+H+(q>>>0<E>>>0?1:0)|0;z=f[7]=z+I|0;f[6]=F+X+(z>>>0<I>>>0?1:0)|0;A=f[9]=A+u|0;f[8]=B+w+(A>>>0<u>>>0?1:0)|
0;P=f[11]=P+J|0;f[10]=C+S+(P>>>0<J>>>0?1:0)|0;Q=f[13]=Q+K|0;f[12]=ga+T+(Q>>>0<K>>>0?1:0)|0;R=f[15]=R+L|0;f[14]=ha+Y+(R>>>0<L>>>0?1:0)|0}
sjcl.mode.ccm={name:"ccm",C:[],listenProgress:function(b){sjcl.mode.ccm.C.push(b)},unListenProgress:function(b){b=sjcl.mode.ccm.C.indexOf(b);-1<b&&sjcl.mode.ccm.C.splice(b,1)},da:function(b){var c=sjcl.mode.ccm.C.slice(),d;for(d=0;d<c.length;d+=1)c[d](b)},encrypt:function(b,c,d,a,e){var f,g=c.slice(0),h=sjcl.bitArray,k=h.bitLength(d)/8,l=h.bitLength(g)/8;e=e||64;a=a||[];if(7>k)throw new sjcl.exception.invalid("ccm: iv must be at least 7 bytes");for(f=2;4>f&&l>>>8*f;f++);f<15-k&&(f=15-k);d=h.clamp(d,
8*(15-f));c=sjcl.mode.ccm.T(b,c,d,a,e,f);g=sjcl.mode.ccm.U(b,g,d,c,e,f);return h.concat(g.data,g.tag)},decrypt:function(b,c,d,a,e){e=e||64;a=a||[];var f=sjcl.bitArray,g=f.bitLength(d)/8,h=f.bitLength(c),k=f.clamp(c,h-e),l=f.bitSlice(c,h-e),h=(h-e)/8;if(7>g)throw new sjcl.exception.invalid("ccm: iv must be at least 7 bytes");for(c=2;4>c&&h>>>8*c;c++);c<15-g&&(c=15-g);d=f.clamp(d,8*(15-c));k=sjcl.mode.ccm.U(b,k,d,l,e,c);b=sjcl.mode.ccm.T(b,k.data,d,a,e,c);if(!f.equal(k.tag,b))throw new sjcl.exception.corrupt("ccm: tag doesn't match");
return k.data},ma:function(b,c,d,a,e,f){var g=[],h=sjcl.bitArray,k=h.P;a=[h.partial(8,(c.length?64:0)|a-2<<2|f-1)];a=h.concat(a,d);a[3]|=e;a=b.encrypt(a);if(c.length)for(d=h.bitLength(c)/8,65279>=d?g=[h.partial(16,d)]:0xffffffff>=d&&(g=h.concat([h.partial(16,65534)],[d])),g=h.concat(g,c),c=0;c<g.length;c+=4)a=b.encrypt(k(a,g.slice(c,c+4).concat([0,0,0])));return a},T:function(b,c,d,a,e,f){var g=sjcl.bitArray,h=g.P;e/=8;if(e%2||4>e||16<e)throw new sjcl.exception.invalid("ccm: invalid tag length");
if(0xffffffff<a.length||0xffffffff<c.length)throw new sjcl.exception.bug("ccm: can't deal with 4GiB or more data");d=sjcl.mode.ccm.ma(b,a,d,e,g.bitLength(c)/8,f);for(a=0;a<c.length;a+=4)d=b.encrypt(h(d,c.slice(a,a+4).concat([0,0,0])));return g.clamp(d,8*e)},U:function(b,c,d,a,e,f){var g,h=sjcl.bitArray;g=h.P;var k=c.length,l=h.bitLength(c),m=k/50,n=m;d=h.concat([h.partial(8,f-1)],d).concat([0,0,0]).slice(0,4);a=h.bitSlice(g(a,b.encrypt(d)),0,e);if(!k)return{tag:a,data:[]};for(g=0;g<k;g+=4)g>m&&(sjcl.mode.ccm.da(g/
k),m+=n),d[3]++,e=b.encrypt(d),c[g]^=e[0],c[g+1]^=e[1],c[g+2]^=e[2],c[g+3]^=e[3];return{tag:a,data:h.clamp(c,l)}}};sjcl.misc.hmac=function(b,c){this.V=c=c||sjcl.hash.sha512;var d=[[],[]],a,e=c.prototype.blockSize/32;this.s=[new c,new c];b.length>e&&(b=c.hash(b));for(a=0;a<e;a++)d[0][a]=b[a]^909522486,d[1][a]=b[a]^1549556828;this.s[0].update(d[0]);this.s[1].update(d[1]);this.O=new c(this.s[0])};
sjcl.misc.hmac.prototype.encrypt=sjcl.misc.hmac.prototype.mac=function(b){if(this.Z)throw new sjcl.exception.invalid("encrypt on already updated hmac called!");this.update(b);return this.digest(b)};sjcl.misc.hmac.prototype.reset=function(){this.O=new this.V(this.s[0]);this.Z=!1};sjcl.misc.hmac.prototype.update=function(b){this.Z=!0;this.O.update(b)};sjcl.misc.hmac.prototype.digest=function(){var b=this.O.finalize(),b=(new this.V(this.s[1])).update(b).finalize();this.reset();return b};
sjcl.misc.pbkdf2=function(b,c,d,a,e){d=d||1E4;if(0>a||0>d)throw new sjcl.exception.invalid("invalid params to pbkdf2");"string"===typeof b&&(b=sjcl.codec.utf8String.toBits(b));"string"===typeof c&&(c=sjcl.codec.utf8String.toBits(c));e=e||sjcl.misc.hmac;b=new e(b);var f,g,h,k,l=[],m=sjcl.bitArray;for(k=1;32*l.length<(a||1);k++){e=f=b.encrypt(m.concat(c,[k]));for(g=1;g<d;g++)for(f=b.encrypt(f),h=0;h<f.length;h++)e[h]^=f[h];l=l.concat(e)}a&&(l=m.clamp(l,a));return l};
sjcl.misc.scrypt=function(b,c,d,a,e,f,g){var h=Math.pow(2,32)-1,k=sjcl.misc.scrypt;d=d||32768;a=a||8;e=e||1;if(a*e>=Math.pow(2,30))throw sjcl.exception.invalid("The parameters r, p must satisfy r * p < 2^30");if(2>d||d&0!=d-1)throw sjcl.exception.invalid("The parameter N must be a power of 2.");if(d>h/128/a)throw sjcl.exception.invalid("N too big.");if(a>h/128/e)throw sjcl.exception.invalid("r too big.");c=sjcl.misc.pbkdf2(b,c,1,128*e*a*8,g);a=c.length/e;k.reverse(c);for(h=0;h<e;h++){var l=c.slice(h*
a,(h+1)*a);k.blockcopy(k.ROMix(l,d),0,c,h*a)}k.reverse(c);return sjcl.misc.pbkdf2(b,c,1,f,g)};
sjcl.misc.scrypt.salsa20Core=function(b,c){function d(a,b){return a<<b|a>>>32-b}for(var a=b.slice(0),e=c;0<e;e-=2)a[4]^=d(a[0]+a[12],7),a[8]^=d(a[4]+a[0],9),a[12]^=d(a[8]+a[4],13),a[0]^=d(a[12]+a[8],18),a[9]^=d(a[5]+a[1],7),a[13]^=d(a[9]+a[5],9),a[1]^=d(a[13]+a[9],13),a[5]^=d(a[1]+a[13],18),a[14]^=d(a[10]+a[6],7),a[2]^=d(a[14]+a[10],9),a[6]^=d(a[2]+a[14],13),a[10]^=d(a[6]+a[2],18),a[3]^=d(a[15]+a[11],7),a[7]^=d(a[3]+a[15],9),a[11]^=d(a[7]+a[3],13),a[15]^=d(a[11]+a[7],18),a[1]^=d(a[0]+a[3],7),a[2]^=
d(a[1]+a[0],9),a[3]^=d(a[2]+a[1],13),a[0]^=d(a[3]+a[2],18),a[6]^=d(a[5]+a[4],7),a[7]^=d(a[6]+a[5],9),a[4]^=d(a[7]+a[6],13),a[5]^=d(a[4]+a[7],18),a[11]^=d(a[10]+a[9],7),a[8]^=d(a[11]+a[10],9),a[9]^=d(a[8]+a[11],13),a[10]^=d(a[9]+a[8],18),a[12]^=d(a[15]+a[14],7),a[13]^=d(a[12]+a[15],9),a[14]^=d(a[13]+a[12],13),a[15]^=d(a[14]+a[13],18);for(e=0;16>e;e++)b[e]=a[e]+b[e]};
sjcl.misc.scrypt.blockMix=function(b){for(var c=b.slice(-16),d=[],a=b.length/16,e=sjcl.misc.scrypt,f=0;f<a;f++)e.blockxor(b,16*f,c,0,16),e.salsa20Core(c,8),0==(f&1)?e.blockcopy(c,0,d,8*f):e.blockcopy(c,0,d,8*(f^1+a));return d};sjcl.misc.scrypt.ROMix=function(b,c){for(var d=b.slice(0),a=[],e=sjcl.misc.scrypt,f=0;f<c;f++)a.push(d.slice(0)),d=e.blockMix(d);for(f=0;f<c;f++)e.blockxor(a[d[d.length-16]&c-1],0,d,0),d=e.blockMix(d);return d};
sjcl.misc.scrypt.reverse=function(b){for(var c in b){var d=b[c]&255,d=d<<8|b[c]>>>8&255,d=d<<8|b[c]>>>16&255,d=d<<8|b[c]>>>24&255;b[c]=d}};sjcl.misc.scrypt.blockcopy=function(b,c,d,a,e){var f;e=e||b.length-c;for(f=0;f<e;f++)d[a+f]=b[c+f]|0};sjcl.misc.scrypt.blockxor=function(b,c,d,a,e){var f;e=e||b.length-c;for(f=0;f<e;f++)d[a+f]=d[a+f]^b[c+f]|0};
sjcl.prng=function(b){this.c=[new sjcl.hash.sha512];this.j=[0];this.N=0;this.D={};this.K=0;this.S={};this.X=this.f=this.l=this.fa=0;this.b=[0,0,0,0,0,0,0,0];this.h=[0,0,0,0];this.I=void 0;this.J=b;this.A=!1;this.H={progress:{},seeded:{}};this.o=this.ea=0;this.F=1;this.G=2;this.aa=0x10000;this.R=[0,48,64,96,128,192,0x100,384,512,768,1024];this.ba=3E4;this.$=80};
sjcl.prng.prototype={randomWords:function(b,c){var d=[],a;a=this.isReady(c);var e;if(a===this.o)throw new sjcl.exception.notReady("generator isn't seeded");if(a&this.G){a=!(a&this.F);e=[];var f=0,g;this.X=e[0]=(new Date).valueOf()+this.ba;for(g=0;16>g;g++)e.push(0x100000000*Math.random()|0);for(g=0;g<this.c.length&&(e=e.concat(this.c[g].finalize()),f+=this.j[g],this.j[g]=0,a||!(this.N&1<<g));g++);this.N>=1<<this.c.length&&(this.c.push(new sjcl.hash.sha512),this.j.push(0));this.f-=f;f>this.l&&(this.l=
f);this.N++;this.b=sjcl.hash.sha512.hash(this.b.concat(e)).slice(0,8);this.I=new sjcl.cipher.aes(this.b);for(a=0;4>a&&(this.h[a]=this.h[a]+1|0,!this.h[a]);a++);}for(a=0;a<b;a+=4)0===(a+1)%this.aa&&ca(this),e=da(this),d.push(e[0],e[1],e[2],e[3]);ca(this);return d.slice(0,b)},setDefaultParanoia:function(b,c){if(0===b&&"Setting paranoia=0 will ruin your security; use it only for testing"!==c)throw new sjcl.exception.invalid("Setting paranoia=0 will ruin your security; use it only for testing");this.J=
b},addEntropy:function(b,c,d){d=d||"user";var a,e,f=(new Date).valueOf(),g=this.D[d],h=this.isReady(),k=0;a=this.S[d];void 0===a&&(a=this.S[d]=this.fa++);void 0===g&&(g=this.D[d]=0);this.D[d]=(this.D[d]+1)%this.c.length;switch(typeof b){case "number":void 0===c&&(c=1);this.c[g].update([a,this.K++,1,c,f,1,b|0]);break;case "object":d=Object.prototype.toString.call(b);if("[object Uint32Array]"===d){e=[];for(d=0;d<b.length;d++)e.push(b[d]);b=e}else for("[object Array]"!==d&&(k=1),d=0;d<b.length&&!k;d++)"number"!==
typeof b[d]&&(k=1);if(!k){if(void 0===c)for(d=c=0;d<b.length;d++)for(e=b[d];0<e;)c++,e=e>>>1;this.c[g].update([a,this.K++,2,c,f,b.length].concat(b))}break;case "string":void 0===c&&(c=b.length);this.c[g].update([a,this.K++,3,c,f,b.length]);this.c[g].update(b);break;default:k=1}if(k)throw new sjcl.exception.bug("random: addEntropy only supports number, array of numbers or string");this.j[g]+=c;this.f+=c;h===this.o&&(this.isReady()!==this.o&&ea("seeded",Math.max(this.l,this.f)),ea("progress",this.getProgress()))},
isReady:function(b){b=this.R[void 0!==b?b:this.J];return this.l&&this.l>=b?this.j[0]>this.$&&(new Date).valueOf()>this.X?this.G|this.F:this.F:this.f>=b?this.G|this.o:this.o},getProgress:function(b){b=this.R[b?b:this.J];return this.l>=b?1:this.f>b?1:this.f/b},startCollectors:function(){if(!this.A){this.a={loadTimeCollector:O(this,this.la),mouseCollector:O(this,this.na),keyboardCollector:O(this,this.ja),accelerometerCollector:O(this,this.ca),touchCollector:O(this,this.pa)};if(window.addEventListener)window.addEventListener("load",
this.a.loadTimeCollector,!1),window.addEventListener("mousemove",this.a.mouseCollector,!1),window.addEventListener("keypress",this.a.keyboardCollector,!1),window.addEventListener("devicemotion",this.a.accelerometerCollector,!1),window.addEventListener("touchmove",this.a.touchCollector,!1);else if(document.attachEvent)document.attachEvent("onload",this.a.loadTimeCollector),document.attachEvent("onmousemove",this.a.mouseCollector),document.attachEvent("keypress",this.a.keyboardCollector);else throw new sjcl.exception.bug("can't attach event");
this.A=!0}},stopCollectors:function(){this.A&&(window.removeEventListener?(window.removeEventListener("load",this.a.loadTimeCollector,!1),window.removeEventListener("mousemove",this.a.mouseCollector,!1),window.removeEventListener("keypress",this.a.keyboardCollector,!1),window.removeEventListener("devicemotion",this.a.accelerometerCollector,!1),window.removeEventListener("touchmove",this.a.touchCollector,!1)):document.detachEvent&&(document.detachEvent("onload",this.a.loadTimeCollector),document.detachEvent("onmousemove",
this.a.mouseCollector),document.detachEvent("keypress",this.a.keyboardCollector)),this.A=!1)},addEventListener:function(b,c){this.H[b][this.ea++]=c},removeEventListener:function(b,c){var d,a,e=this.H[b],f=[];for(a in e)e.hasOwnProperty(a)&&e[a]===c&&f.push(a);for(d=0;d<f.length;d++)a=f[d],delete e[a]},ja:function(){U(this,1)},na:function(b){var c,d;try{c=b.x||b.clientX||b.offsetX||0,d=b.y||b.clientY||b.offsetY||0}catch(a){d=c=0}0!=c&&0!=d&&this.addEntropy([c,d],2,"mouse");U(this,0)},pa:function(b){b=
b.touches[0]||b.changedTouches[0];this.addEntropy([b.pageX||b.clientX,b.pageY||b.clientY],1,"touch");U(this,0)},la:function(){U(this,2)},ca:function(b){b=b.accelerationIncludingGravity.x||b.accelerationIncludingGravity.y||b.accelerationIncludingGravity.z;if(window.orientation){var c=window.orientation;"number"===typeof c&&this.addEntropy(c,1,"accelerometer")}b&&this.addEntropy(b,2,"accelerometer");U(this,0)}};
function ea(b,c){var d,a=sjcl.random.H[b],e=[];for(d in a)a.hasOwnProperty(d)&&e.push(a[d]);for(d=0;d<e.length;d++)e[d](c)}function U(b,c){"undefined"!==typeof window&&window.performance&&"function"===typeof window.performance.now?b.addEntropy(window.performance.now(),c,"loadtime"):b.addEntropy((new Date).valueOf(),c,"loadtime")}function ca(b){b.b=da(b).concat(da(b));b.I=new sjcl.cipher.aes(b.b)}function da(b){for(var c=0;4>c&&(b.h[c]=b.h[c]+1|0,!b.h[c]);c++);return b.I.encrypt(b.h)}
function O(b,c){return function(){c.apply(b,arguments)}}sjcl.random=new sjcl.prng(8);
a:try{var V,fa,W,ka;if(ka="undefined"!==typeof module&&module.exports){var la;try{la=require("crypto")}catch(b){la=null}ka=fa=la}if(ka&&fa.randomBytes)V=fa.randomBytes(128),V=new Uint32Array((new Uint8Array(V)).buffer),sjcl.random.addEntropy(V,1024,"crypto['randomBytes']");else if("undefined"!==typeof window&&"undefined"!==typeof Uint32Array){W=new Uint32Array(32);if(window.crypto&&window.crypto.getRandomValues)window.crypto.getRandomValues(W);else if(window.msCrypto&&window.msCrypto.getRandomValues)window.msCrypto.getRandomValues(W);
else break a;sjcl.random.addEntropy(W,1024,"crypto['getRandomValues']")}}catch(b){"undefined"!==typeof window&&window.console&&(console.log("There was an error collecting entropy from the browser:"),console.log(b))}
sjcl.json={defaults:{v:1,iter:1E4,ks:0x100,ts:128,mode:"ccm",adata:"",cipher:"aes"},ha:function(b,c,d,a){d=d||{};a=a||{};var e=sjcl.json,f=e.g({iv:sjcl.random.randomWords(4,0)},e.defaults),g;e.g(f,d);d=f.adata;"string"===typeof f.salt&&(f.salt=sjcl.codec.base64.toBits(f.salt));"string"===typeof f.iv&&(f.iv=sjcl.codec.base64.toBits(f.iv));if(!sjcl.mode[f.mode]||!sjcl.cipher[f.cipher]||"string"===typeof b&&100>=f.iter||64!==f.ts&&96!==f.ts&&128!==f.ts||128!==f.ks&&192!==f.ks&&0x100!==f.ks||2>f.iv.length||
4<f.iv.length)throw new sjcl.exception.invalid("json encrypt: invalid parameters");"string"===typeof b?(g=sjcl.misc.cachedPbkdf2(b,f),b=g.key.slice(0,f.ks/32),f.salt=g.salt):sjcl.ecc&&b instanceof sjcl.ecc.elGamal.publicKey&&(g=b.kem(),f.kemtag=g.tag,b=g.key.slice(0,f.ks/32));"string"===typeof c&&(c=sjcl.codec.utf8String.toBits(c));"string"===typeof d&&(f.adata=d=sjcl.codec.utf8String.toBits(d));g=new sjcl.cipher[f.cipher](b);e.g(a,f);a.key=b;f.ct="ccm"===f.mode&&sjcl.arrayBuffer&&sjcl.arrayBuffer.ccm&&
c instanceof ArrayBuffer?sjcl.arrayBuffer.ccm.encrypt(g,c,f.iv,d,f.ts):sjcl.mode[f.mode].encrypt(g,c,f.iv,d,f.ts);return f},encrypt:function(b,c,d,a){var e=sjcl.json,f=e.ha.apply(e,arguments);return e.encode(f)},ga:function(b,c,d,a){d=d||{};a=a||{};var e=sjcl.json;c=e.g(e.g(e.g({},e.defaults),c),d,!0);var f,g;f=c.adata;"string"===typeof c.salt&&(c.salt=sjcl.codec.base64.toBits(c.salt));"string"===typeof c.iv&&(c.iv=sjcl.codec.base64.toBits(c.iv));if(!sjcl.mode[c.mode]||!sjcl.cipher[c.cipher]||"string"===
typeof b&&100>=c.iter||64!==c.ts&&96!==c.ts&&128!==c.ts||128!==c.ks&&192!==c.ks&&0x100!==c.ks||!c.iv||2>c.iv.length||4<c.iv.length)throw new sjcl.exception.invalid("json decrypt: invalid parameters");"string"===typeof b?(g=sjcl.misc.cachedPbkdf2(b,c),b=g.key.slice(0,c.ks/32),c.salt=g.salt):sjcl.ecc&&b instanceof sjcl.ecc.elGamal.secretKey&&(b=b.unkem(sjcl.codec.base64.toBits(c.kemtag)).slice(0,c.ks/32));"string"===typeof f&&(f=sjcl.codec.utf8String.toBits(f));g=new sjcl.cipher[c.cipher](b);f="ccm"===
c.mode&&sjcl.arrayBuffer&&sjcl.arrayBuffer.ccm&&c.ct instanceof ArrayBuffer?sjcl.arrayBuffer.ccm.decrypt(g,c.ct,c.iv,c.tag,f,c.ts):sjcl.mode[c.mode].decrypt(g,c.ct,c.iv,f,c.ts);e.g(a,c);a.key=b;return 1===d.raw?f:sjcl.codec.utf8String.fromBits(f)},decrypt:function(b,c,d,a){var e=sjcl.json;return e.ga(b,e.decode(c),d,a)},encode:function(b){var c,d="{",a="";for(c in b)if(b.hasOwnProperty(c)){if(!c.match(/^[a-z0-9]+$/i))throw new sjcl.exception.invalid("json encode: invalid property name");d+=a+'"'+
c+'":';a=",";switch(typeof b[c]){case "number":case "boolean":d+=b[c];break;case "string":d+='"'+escape(b[c])+'"';break;case "object":d+='"'+sjcl.codec.base64.fromBits(b[c],0)+'"';break;default:throw new sjcl.exception.bug("json encode: unsupported type");}}return d+"}"},decode:function(b){b=b.replace(/\s/g,"");if(!b.match(/^\{.*\}$/))throw new sjcl.exception.invalid("json decode: this isn't json!");b=b.replace(/^\{|\}$/g,"").split(/,/);var c={},d,a;for(d=0;d<b.length;d++){if(!(a=b[d].match(/^\s*(?:(["']?)([a-z][a-z0-9]*)\1)\s*:\s*(?:(-?\d+)|"([a-z0-9+\/%*_.@=\-]*)"|(true|false))$/i)))throw new sjcl.exception.invalid("json decode: this isn't json!");
null!=a[3]?c[a[2]]=parseInt(a[3],10):null!=a[4]?c[a[2]]=a[2].match(/^(ct|adata|salt|iv)$/)?sjcl.codec.base64.toBits(a[4]):unescape(a[4]):null!=a[5]&&(c[a[2]]="true"===a[5])}return c},g:function(b,c,d){void 0===b&&(b={});if(void 0===c)return b;for(var a in c)if(c.hasOwnProperty(a)){if(d&&void 0!==b[a]&&b[a]!==c[a])throw new sjcl.exception.invalid("required parameter overridden");b[a]=c[a]}return b},ra:function(b,c){var d={},a;for(a in b)b.hasOwnProperty(a)&&b[a]!==c[a]&&(d[a]=b[a]);return d},qa:function(b,
c){var d={},a;for(a=0;a<c.length;a++)void 0!==b[c[a]]&&(d[c[a]]=b[c[a]]);return d}};sjcl.encrypt=sjcl.json.encrypt;sjcl.decrypt=sjcl.json.decrypt;sjcl.misc.oa={};sjcl.misc.cachedPbkdf2=function(b,c){var d=sjcl.misc.oa,a;c=c||{};a=c.iter||1E3;d=d[b]=d[b]||{};a=d[a]=d[a]||{firstSalt:c.salt&&c.salt.length?c.salt.slice(0):sjcl.random.randomWords(2,0)};d=void 0===c.salt?a.firstSalt:c.salt;a[d]=a[d]||sjcl.misc.pbkdf2(b,d,c.iter);return{key:a[d].slice(0),salt:d.slice(0)}};
"undefined"!==typeof module&&module.exports&&(module.exports=sjcl);"function"===typeof define&&define([],function(){return sjcl});
